name: Build Flet App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"
          channel: stable
          cache: true

      - name: Install dependencies for Linux toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev liblzma-dev

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses || true

      # Build Web
      - name: Build Web App
        run: flutter build web --release

      # Build Android APK
      - name: Build Android APK
        run: flutter build apk --release

      # Build Linux Desktop App
      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Build Linux App
        run: flutter build linux --release

      # Upload Web Build
      - name: Upload Web Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web

      # Upload Android APK
      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Upload Linux Build
      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: build/linux/x64/release
